# Generated by Django 4.2.6 on 2023-11-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('HA', 'Hito Academico'), ('SA', 'Suspension de Actividades'), ('EDDA', 'EDDA'), ('EV', 'Evaluacion'), ('AY', 'Ayudantias'), ('SAPM', 'Suspension de actividades PM'), ('SAC', 'Secretaria Academica'), ('OAI', 'OAI'), ('V', 'Vacaciones'), ('C', 'Ceremonia'), ('F', 'Feriado'), ('SE', 'Suspension de Evaluaciones')], max_length=20)),
                ('segmento', models.CharField(choices=[('ES', 'Estudiante'), ('JC', 'Jefe de Carrera'), ('PR', 'Profesor'), ('CU', 'Comunidad USM')], max_length=20)),
            ],
        ),
    ]
