# Generated by Django 4.2.6 on 2023-11-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=[('CU', 'Comunidad USM'), ('PR', 'Profesor'), ('ES', 'Estudiante'), ('JC', 'Jefe de Carrera')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='segmento',
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('SAC', 'Secretaria Academica'), ('SA', 'Suspension de Actividades'), ('F', 'Feriado'), ('AY', 'Ayudantias'), ('V', 'Vacaciones'), ('EV', 'Evaluacion'), ('EDDA', 'EDDA'), ('SE', 'Suspension de Evaluaciones'), ('OAI', 'OAI'), ('C', 'Ceremonia'), ('SAPM', 'Suspension de actividades PM'), ('HA', 'Hito Academico')], max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='segmento',
            field=models.ManyToManyField(to='miapp.segmento'),
        ),
    ]
