# Generated by Django 4.2.7 on 2023-11-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_segmento_remove_evento_segmento_alter_evento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('EDDA', 'EDDA'), ('EV', 'Evaluacion'), ('F', 'Feriado'), ('SE', 'Suspension de Evaluaciones'), ('C', 'Ceremonia'), ('SA', 'Suspension de Actividades'), ('HA', 'Hito Academico'), ('SAC', 'Secretaria Academica'), ('SAPM', 'Suspension de actividades PM'), ('OAI', 'OAI'), ('V', 'Vacaciones'), ('AY', 'Ayudantias')], max_length=20),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='segmento',
            field=models.CharField(choices=[('JC', 'Jefe de Carrera'), ('ES', 'Estudiante'), ('CU', 'Comunidad USM'), ('PR', 'Profesor')], max_length=20),
        ),
    ]
