# Generated by Django 4.2.6 on 2023-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_segmento_remove_evento_segmento_alter_evento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('F', 'Feriado'), ('V', 'Vacaciones'), ('SE', 'Suspension de Evaluaciones'), ('EDDA', 'EDDA'), ('SAPM', 'Suspension de actividades PM'), ('C', 'Ceremonia'), ('EV', 'Evaluacion'), ('AY', 'Ayudantias'), ('HA', 'Hito Academico'), ('OAI', 'OAI'), ('SAC', 'Secretaria Academica'), ('SA', 'Suspension de Actividades')], max_length=20),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='segmento',
            field=models.CharField(choices=[('ES', 'Estudiante'), ('JC', 'Jefe de Carrera'), ('PR', 'Profesor'), ('CU', 'Comunidad USM')], max_length=20),
        ),
    ]
