# Generated by Django 4.2.7 on 2023-11-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_evento_tipo_alter_segmento_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('V', 'Vacaciones'), ('AY', 'Ayudantias'), ('SAC', 'Secretaria Academica'), ('SA', 'Suspension de Actividades'), ('SE', 'Suspension de Evaluaciones'), ('SAPM', 'Suspension de actividades PM'), ('OAI', 'OAI'), ('F', 'Feriado'), ('EDDA', 'EDDA'), ('C', 'Ceremonia'), ('HA', 'Hito Academico'), ('EV', 'Evaluacion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='segmento',
            field=models.CharField(choices=[('JC', 'Jefe de Carrera'), ('PR', 'Profesor'), ('ES', 'Estudiante'), ('CU', 'Comunidad USM')], max_length=20),
        ),
    ]
