# Generated by Django 4.2.6 on 2023-11-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_evento_tipo_alter_segmento_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('SE', 'Suspension de Evaluaciones'), ('AY', 'Ayudantias'), ('HA', 'Hito Academico'), ('V', 'Vacaciones'), ('EV', 'Evaluacion'), ('SA', 'Suspension de Actividades'), ('OAI', 'OAI'), ('EDDA', 'EDDA'), ('SAPM', 'Suspension de actividades PM'), ('SAC', 'Secretaria Academica'), ('C', 'Ceremonia'), ('F', 'Feriado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='segmento',
            field=models.CharField(choices=[('CU', 'Comunidad USM'), ('ES', 'Estudiante'), ('JC', 'Jefe de Carrera'), ('PR', 'Profesor')], max_length=20),
        ),
    ]
